const state = {
    gradovi: [
        "Bakar",
        "Beli Manastir",
        "Belišće",
        "Benkovac",
        "Bjelovar",
        "Buje",
        "Buzet",
        "Cres",
        "Crikvenica",
        "Čabar",
        "Čakovec",
        "Čazma",
        "Daruvar",
        "Delnice",
        "Donja Stubica",
        "Donji Miholjac",
        "Drniš",
        "Dubrovnik",
        "Duga Resa",
        "Dugo Selo",
        "Đakovo",
        "Đurđevac",
        "Garešnica",
        "Glina",
        "Gospić",
        "Grubišno Polje",
        "Hrvatska Kostajnica",
        "Hvar",
        "Ilok",
        "Imotski",
        "Ivanec",
        "Jastrebarsko",
        "Karlovac",
        "Kastav",
        "Klanjec",
        "Knin",
        "Komiža",
        "Koprivnica",
        "Korčula",
        "Kraljevica",
        "Krapina",
        "Križevci",
        "Krk",
        "Kutina",
        "Kutjevo",
        "Labin",
        "Lepoglava",
        "Lipik",
        "Ludbreg",
        "Makarska",
        "Mali Lošinj",
        "Metković",
        "Mursko Središće",
        "Našice",
        "Nin",
        "Nova Gradiška",
        "Novalja",
        "Novi Marof",
        "Novi Vinodolski",
        "Novigrad",
        "Novska",
        "Obrovac",
        "Ogulin",
        "Omiš",
        "Opatija",
        "Opuzen",
        "Orahovica",
        "Oroslavje",
        "Osijek",
        "Otočac",
        "Otok",
        "Ozalj",
        "Pag",
        "Pakrac",
        "Pazin",
        "Petrinja",
        "Pleternica",
        "Ploče",
        "Popovača",
        "Poreč",
        "Požega",
        "Pregrada",
        "Prelog",
        "Pula",
        "Rab",
        "Rijeka",
        "Rovinj",
        "Samobor",
        "Senj",
        "Sinj",
        "Sisak",
        "Skradin",
        "Slatina",
        "Slavonski Brod",
        "Slunj",
        "Solin",
        "Split",
        "Stari Grad",
        "Supetar",
        "Sveti Ivan Zelina",
        "Šibenik",
        "Trilj",
        "Trogir",
        "Umag",
        "Valpovo",
        "Varaždin",
        "Varaždinske Toplice",
        "Velika Gorica",
        "Vinkovci",
        "Virovitica",
        "Vis",
        "Vodice",
        "Vodnjan",
        "Vrbovec",
        "Vrbovsko",
        "Vrgorac",
        "Vrlika",
        "Vukovar",
        "Zabok",
        "Zadar",
        "Zaprešić",
        "Zlatar",
        "Županja",
        "Zagreb",
    ]
  };
    
  const getters = {
    getGradovi(store){
        return store.gradovi
    }
  };
  const actions = {
    
  };
  const mutations = {
    
  };
  export default {
    state,
    getters,
    actions,
    mutations
  };
  